name: real_picknplace_image

image_shape: &image_shape [3, 240, 320]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: *image_shape
      type: rgb
    camera_1:
      shape: *image_shape
      type: rgb
    robot_eef_pose:
      shape: [6]
      type: low_dim
  action:
    shape: [7]

env_runner:
  _target_: shared.env.picknplace.picknplace_image_runner.PickNPlaceImageRunner
  output_dir: ${hydra:runtime.output_dir}

dataset:
  _target_: shared.env.picknplace.picknplace_image_dataset.PickNPlaceImageDataset
  dataset_path: data/picknplace_80
  shape_meta: *shape_meta
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 80
  num_obs_steps: ${dataset_obs_steps}
  num_latency_steps: ${num_latency_steps}
  delta_action: True

