name: real_pushblock_image

image_shape: &image_shape [3, 240, 320]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: *image_shape
      type: rgb
    camera_1:
      shape: *image_shape
      type: rgb
    robot_eef_pose:
      shape: [6]
      type: low_dim
  action:
    shape: [6]

env_runner:
  _target_: shared.env.pushblock.pushblock_image_runner.PushBlockImageRunner
  output_dir: ${hydra:runtime.output_dir}

dataset:
  _target_: shared.env.pushblock.pushblock_image_dataset.PushBlockImageDataset
  dataset_path: data/pushblock_50_seed_371
  shape_meta: *shape_meta
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 371
  val_ratio: 0.00
  max_train_episodes: 50
  num_obs_steps: ${dataset_obs_steps}
  num_latency_steps: ${num_latency_steps}
  delta_action: True

